// Định nghĩa các action types

export const UPDATE_USER_LIST_PENDING = "user/UPDATE_USER_LIST_PENDING";
export const UPDATE_USER_LIST_FULFILLED = "user/UPDATE_USER_LIST_FULFILLED";
export const UPDATE_USER_LIST_REJECTED = "user/UPDATE_USER_LIST_REJECTED";

export const UPDATE_SELECTED_USER = "user/UPDATE_SELECTED_USER";
export const UPDATE_SEARCH_TERM = "user/UPDATE_SEARCH_TERM"